name: Frontend CI

on:
  push:
    branches: [main]
    paths:
      - "frontend/**"
  pull_request:
    branches: [main]
    paths:
      - "frontend/**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.19.x"
          channel: "stable"

      - name: Install Melos
        run: dart pub global activate melos

      - name: Install dependencies
        run: cd frontend && melos bs

      - name: Test
        run: cd frontend && melos test

  build-web:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.19.x"
          channel: "stable"

      - name: Install Melos
        run: dart pub global activate melos

      - name: Install dependencies
        run: cd frontend && melos bs

      - name: Build Web
        run: cd frontend/app && flutter build web --release

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: web-build
          path: frontend/app/build/web
